spring.application.name=TechStore

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/techstore
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# (Opcional) Formatear el SQL en consola
spring.jpa.properties.hibernate.format_sql=true